const products = [  {
    "Channel": "Nykaa",
    "Style Number": 24034,
    "Size": "5XL",
    "Color": "Red",
    "Brand": "Qurvii Desi",
    "Date": "28-04-2025 12:51",
    "Pattern#": "108 (D)",
    "Style Type": "Dress",
    "Style Name": "Red silk Kimono dress with brocade",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39831,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39831"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 24020,
    "Size": "3XL",
    "Color": "Royal Blue",
    "Brand": "Qurvii Desi",
    "Date": "28-04-2025 12:51",
    "Pattern#": "108(D)",
    "Style Type": "Dress",
    "Style Name": "Royal Blue & Green colorblock silk Kimono oversize dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39830,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39830"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19321,
    "Size": "4XL",
    "Color": "Magenta",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 858,
    "Style Type": "Shirt",
    "Style Name": "Magenta stripe oversized shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39829,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39829"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19317,
    "Size": "L",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 854,
    "Style Type": "Dress",
    "Style Name": "Black Polka & Stripe Oversized Dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39828,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39828"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 19303,
    "Size": "5XL",
    "Color": "Green",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 815,
    "Style Type": "Dress",
    "Style Name": "Contrast Green Geometrical Print Dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39764,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39764"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19299,
    "Size": "M",
    "Color": "Yellow",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 858,
    "Style Type": "Shirt",
    "Style Name": "Yellow Stripe oversized Shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39827,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39827"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19296,
    "Size": "XL",
    "Color": "Navy",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 858,
    "Style Type": "Shirt",
    "Style Name": "Navy & White Stripe oversized Shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39826,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39826"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19276,
    "Size": "4XL",
    "Color": "Brown",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 614,
    "Style Type": "Dress",
    "Style Name": "Brown A-Line Cotton Dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39825,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39825"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19271,
    "Size": "L",
    "Color": "Green",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 755,
    "Style Type": "Shirt",
    "Style Name": "green cotton regular shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39824,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39824"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19265,
    "Size": "L",
    "Color": "Orange",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 755,
    "Style Type": "Shirt",
    "Style Name": "Orange cotton regular shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39823,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39823"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19263,
    "Size": "L",
    "Color": "Indigo Blue",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 755,
    "Style Type": "Shirt",
    "Style Name": "Cotton blue regular shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39822,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39822"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19249,
    "Size": "L",
    "Color": "Brown",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39821,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39821"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19213,
    "Size": "3XL",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 823,
    "Style Type": "Dress",
    "Style Name": "Black halter neck bodycon dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Elastic",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39820,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39820"
  },
  {
    "Channel": "Shopify",
    "Style Number": 19129,
    "Size": "XL",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "Black and yellow leopard print half placket mandarin collar shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39743,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39743"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 19128,
    "Size": "XL",
    "Color": "Green",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 862,
    "Style Type": "Shirt",
    "Style Name": "Solid Green crepe half placket maindarin collar shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39760,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39760"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19128,
    "Size": "2XL",
    "Color": "Green",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 862,
    "Style Type": "Shirt",
    "Style Name": "Solid Green crepe half placket maindarin collar shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39817,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39817"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19128,
    "Size": "L",
    "Color": "Green",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 862,
    "Style Type": "Shirt",
    "Style Name": "Solid Green crepe half placket maindarin collar shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39818,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39818"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19128,
    "Size": "L",
    "Color": "Green",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 862,
    "Style Type": "Shirt",
    "Style Name": "Solid Green crepe half placket maindarin collar shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39837,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39837"
  },
  {
    "Channel": "Shopify",
    "Style Number": 19108,
    "Size": "5XL",
    "Color": "Burgundy",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 10142,
    "Style Type": "Shrug",
    "Style Name": "Burgundy georgette Silver Lurex Party shrug",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39739,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39739"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19102,
    "Size": "XL",
    "Color": "Lavender",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 519,
    "Style Type": "Dress",
    "Style Name": "Lavender Sequins Yoke party Maxi dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Zips",
    "Accessory 2": "",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39816,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39816"
  },
  {
    "Channel": "Shopify",
    "Style Number": 19097,
    "Size": "5XL",
    "Color": "Red",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 10142,
    "Style Type": "Shrug",
    "Style Name": "Red georgette festive party shrug",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39738,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39738"
  },
  {
    "Channel": "Shopify",
    "Style Number": 19091,
    "Size": "4XL",
    "Color": "Multi",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 802,
    "Style Type": "Top",
    "Style Name": "V-Neck Vertical Stripe Top",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Zips",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39737,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39737"
  },
  {
    "Channel": "Shopify",
    "Style Number": 19086,
    "Size": "3XL",
    "Color": "Brown",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 799,
    "Style Type": "Dress",
    "Style Name": "A-line dress with tie knot collar",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39735,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39735"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 19085,
    "Size": "5XL",
    "Color": "White",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 800,
    "Style Type": "Dress",
    "Style Name": "Sparkle A-line Block Dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39759,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39759"
  },
  {
    "Channel": "Shopify",
    "Style Number": 19084,
    "Size": "3XL",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 797,
    "Style Type": "Top",
    "Style Name": "Solid black peter pan collar top with puffed sleeves",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Elastic",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39734,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39734"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 19066,
    "Size": "XL",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 792,
    "Style Type": "Dress",
    "Style Name": "Black slit dress with sequin embellishment",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39758,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39758"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19057,
    "Size": "5XL",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 751,
    "Style Type": "Dress",
    "Style Name": "Multi big polka georgette V-neck A-line calf-length dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39810,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39810"
  },
  {
    "Channel": "Shopify",
    "Style Number": 19048,
    "Size": "4XL",
    "Color": "Gray",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 783,
    "Style Type": "Top",
    "Style Name": "V-Shape Hemline Color Block Kimono Sleeves Top",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39733,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39733"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19027,
    "Size": "4XL",
    "Color": "Navy",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 763,
    "Style Type": "Dress",
    "Style Name": "Navy and white big polka A-line dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39808,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39808"
  },
  {
    "Channel": "Shopify",
    "Style Number": 19017,
    "Size": "XL",
    "Color": "Ivory",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "Ivory and black printed rayon half placket mandarin collar shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39732,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39732"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 19013,
    "Size": "3XL",
    "Color": "Blue",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 692,
    "Style Type": "Dress",
    "Style Name": "Blue and Rust floral below knee length kaftan dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Tassale",
    "Accessory 2": "",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39756,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39756"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 19003,
    "Size": "4XL",
    "Color": "Brown",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 763,
    "Style Type": "Dress",
    "Style Name": "Brown and white big polka A-line dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39755,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39755"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 19003,
    "Size": "2XL",
    "Color": "Brown",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 763,
    "Style Type": "Dress",
    "Style Name": "Brown and white big polka A-line dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39803,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39803"
  },
  {
    "Channel": "Shopify",
    "Style Number": 18093,
    "Size": "S",
    "Color": "Navy",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 751,
    "Style Type": "Dress",
    "Style Name": "Navy and White Big polka georgette V-neck A-line calf-length dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39731,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39731"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 18093,
    "Size": "5XL",
    "Color": "Navy",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 751,
    "Style Type": "Dress",
    "Style Name": "Navy and White Big polka georgette V-neck A-line calf-length dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39752,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39752"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18093,
    "Size": "2XL",
    "Color": "Navy",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 751,
    "Style Type": "Dress",
    "Style Name": "Navy and White Big polka georgette V-neck A-line calf-length dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39801,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39801"
  },
  {
    "Channel": "Shopify",
    "Style Number": 18077,
    "Size": "2XL",
    "Color": "Multi",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "Multi big polka georgette half placket mandarin collar shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39729,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39729"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18077,
    "Size": "2XL",
    "Color": "Multi",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "Multi big polka georgette half placket mandarin collar shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39798,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39798"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18077,
    "Size": "XL",
    "Color": "Multi",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "Multi big polka georgette half placket mandarin collar shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39799,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39799"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18069,
    "Size": "5XL",
    "Color": "Rust",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 519,
    "Style Type": "Dress",
    "Style Name": "Rust floral print dress with a faux wrap-around dress.",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Zips",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39795,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39795"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18069,
    "Size": "M",
    "Color": "Rust",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 519,
    "Style Type": "Dress",
    "Style Name": "Rust floral print dress with a faux wrap-around dress.",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Zips",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39796,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39796"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18069,
    "Size": "XL",
    "Color": "Rust",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 519,
    "Style Type": "Dress",
    "Style Name": "Rust floral print dress with a faux wrap-around dress.",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Zips",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39797,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39797"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18069,
    "Size": "M",
    "Color": "Rust",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 519,
    "Style Type": "Dress",
    "Style Name": "Rust floral print dress with a faux wrap-around dress.",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Zips",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39834,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39834"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18069,
    "Size": "XL",
    "Color": "Rust",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 519,
    "Style Type": "Dress",
    "Style Name": "Rust floral print dress with a faux wrap-around dress.",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Zips",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39835,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39835"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18026,
    "Size": "2XL",
    "Color": "Off White",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 750,
    "Style Type": "Dress",
    "Style Name": "Stylish Off White & black houndstooth midi dress.",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Metal Rings",
    "Accessory 2": "",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39791,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39791"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18026,
    "Size": "XL",
    "Color": "Off White",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 750,
    "Style Type": "Dress",
    "Style Name": "Stylish Off White & black houndstooth midi dress.",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Metal Rings",
    "Accessory 2": "",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39793,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39793"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18025,
    "Size": "L",
    "Color": "Multi",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 698,
    "Style Type": "Shirt",
    "Style Name": "Multi georgette kaftan top with lace",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Lace",
    "Accessory 2": "Fusing",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39788,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39788"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 18025,
    "Size": "M",
    "Color": "Multi",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 698,
    "Style Type": "Shirt",
    "Style Name": "Multi georgette kaftan top with lace",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Lace",
    "Accessory 2": "Fusing",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39789,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39789"
  },
  {
    "Channel": "Shopify",
    "Style Number": 17067,
    "Size": "3XL",
    "Color": "Rust",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "Rust and white polka dot half placket shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39728,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39728"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 17063,
    "Size": "XL",
    "Color": "Blue",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "Blue Japnese floral print half placket shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "Buttons",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39785,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39785"
  },
  {
    "Channel": "Shopify",
    "Style Number": 17023,
    "Size": "4XL",
    "Color": "Pink",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "Navy and Pink polka dott half placket shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39727,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39727"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 17023,
    "Size": "S",
    "Color": "Pink",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "Navy and Pink polka dott half placket shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39784,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39784"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 17022,
    "Size": "2XL",
    "Color": "Burgundy",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 721,
    "Style Type": "Shirt",
    "Style Name": "Burgundy and white polka dott half placket shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39783,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39783"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 16087,
    "Size": "XL",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 626,
    "Style Type": "Dress",
    "Style Name": "Black Long Party Dress with gold shouder chain straps",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Metal Chain",
    "Accessory 2": "",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39782,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39782"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 16085,
    "Size": "XL",
    "Color": "Orange",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 518,
    "Style Type": "Shirt",
    "Style Name": "Orange satin floral print mandrain collar shirt with full cuff sleeves",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39781,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39781"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 16056,
    "Size": "XL",
    "Color": "Maroon",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 10139,
    "Style Type": "Dress",
    "Style Name": "Maroon silk A-Line sequins embelished V neck swing dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39780,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39780"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 16027,
    "Size": "M",
    "Color": "Ivory",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 689,
    "Style Type": "Coat",
    "Style Name": "Ivory fleece long coat with pockets",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39775,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39775"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 16027,
    "Size": "XL",
    "Color": "Ivory",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 689,
    "Style Type": "Coat",
    "Style Name": "Ivory fleece long coat with pockets",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39777,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39777"
  },
  {
    "Channel": "Shopify",
    "Style Number": 16009,
    "Size": "L",
    "Color": "Red",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 10142,
    "Style Type": "Shrug",
    "Style Name": "Red Tropical Resort Shrug",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39726,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39726"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 15096,
    "Size": "L",
    "Color": "Multi",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 518,
    "Style Type": "Shirt",
    "Style Name": "Qurvii women Multi abstract print half placket shirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "Fusing",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39774,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39774"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 15031,
    "Size": "3XL",
    "Color": "Red",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 10139,
    "Style Type": "Dress",
    "Style Name": "A-line red dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39772,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39772"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 15031,
    "Size": "3XL",
    "Color": "Red",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 10139,
    "Style Type": "Dress",
    "Style Name": "A-line red dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39773,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39773"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 14094,
    "Size": "5XL",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 689,
    "Style Type": "Jacket",
    "Style Name": "Solid black fleece long jacket",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39770,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39770"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 14094,
    "Size": "5XL",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 689,
    "Style Type": "Jacket",
    "Style Name": "Solid black fleece long jacket",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Fusing",
    "Accessory 2": "",
    "Wash Care": "Hand Wash",
    "": "",
    "(Do not touch) Order Id": 39832,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39832"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 14083,
    "Size": "3XL",
    "Color": "Orange",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 692,
    "Style Type": "Kaftan",
    "Style Name": "Orange floral kaftan",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Tassale",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39748,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39748"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 14072,
    "Size": "3XL",
    "Color": "Purple",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 518,
    "Style Type": "Top",
    "Style Name": "Purple half placket top",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39747,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39747"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 13069,
    "Size": "3XL",
    "Color": "Pink",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 758,
    "Style Type": "Dress",
    "Style Name": "Colorblock A Line Silk Dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Dry Clean Only",
    "": "",
    "(Do not touch) Order Id": 39769,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39769"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 13057,
    "Size": "XL",
    "Color": "Red",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 562,
    "Style Type": "Top",
    "Style Name": "Red Mesh Bell Sleeve Top",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39768,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39768"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 13049,
    "Size": "XL",
    "Color": "Blue",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 631,
    "Style Type": "Skirt",
    "Style Name": "Navy Polka Short Skirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Zips",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39767,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39767"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 13045,
    "Size": "XL",
    "Color": "Burgundy",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 631,
    "Style Type": "Skirt",
    "Style Name": "Burgundy Polka Short Skirt",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Zips",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39766,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39766"
  },
  {
    "Channel": "Nykaa",
    "Style Number": 12095,
    "Size": "3XL",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 626,
    "Style Type": "Dress",
    "Style Name": "Black Solid Long Dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Zips",
    "Accessory 2": "Buckle",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39765,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39765"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 12027,
    "Size": "2XL",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 562,
    "Style Type": "Top",
    "Style Name": "Black Top With Mesh On Bell Sleeves",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39746,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39746"
  },
  {
    "Channel": "TataCliq",
    "Style Number": 12018,
    "Size": "3XL",
    "Color": "Red",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 10139,
    "Style Type": "Dress",
    "Style Name": "Red Polka Dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39745,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39745"
  },
  {
    "Channel": "Shopify",
    "Style Number": 11184,
    "Size": "L",
    "Color": "Black",
    "Brand": "Qurvii",
    "Date": "28-04-2025 12:51",
    "Pattern#": 542,
    "Style Type": "Dress",
    "Style Name": "Striped Button Front Shirt Dress",
    "Style 1": "",
    "Style 2": "",
    "Accessory 1": "Buttons",
    "Accessory 2": "",
    "Wash Care": "Machine Wash",
    "": "",
    "(Do not touch) Order Id": 39724,
    "__1": "",
    "image 100x100 qr image": "https://quickchart.io/qr?text=39724"
  }
]
